### PR TITLE
fix: adds AUR info, removes typo

### LINKED ISSUE #2: [discussion] add this package to AUR
Would you mind adding this package to [AUR](https://aur.archlinux.org/)?

I have a [Plymouth theme](https://aur.archlinux.org/packages/plymouth-theme-aregression/). If you're busy I wouldn't mind adding [`sddm-astronaut`](https://github.com/totoro-ghost/sddm-astronaut/) to AUR.

### PR DESCRIPTION
**Pull request by nandgator**
fixes #2, #3

### CODE REVIEW

**Review by RaZ0rr-Two — CHANGES_REQUESTED** [review]
Maybe change 

> Edit the `/etc/sddm.conf` with [nano](https://www.nano-editor.org) or [micro](https://micro-editor.github.io) so that it looks like this

With 

> Edit the `/etc/sddm.conf` ( using [micro](https://micro-editor.github.io) here)  so that it looks like this

:

**Comment by RaZ0rr-Two** [comment]
[Partial upgrades can break system](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported).

Is `yay -Sy` safe ?

**Comment by nandgator** [comment]
> [Partial upgrades can break system](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported).
> 
> Is `yay -Sy` safe ?

I've been doing it for quite some time, didn't face any issues yet. Anyway the requested changes are included.

**Comment by RaZ0rr-Two** [comment]
> > [Partial upgrades can break system](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported).
> > Is `yay -Sy` safe ?
> 
> I've been doing it for quite some time, didn't face any issues yet. Anyway the requested changes are included.

Thank you for the fixes. From yay documentation :

`yay` 	Alias to `yay -Syu`

**Comment by RaZ0rr-Two** [comment]
I have also added a comment in AUR package about a missing dependency.

**Comment by nandgator** [comment]
> I have also added a comment in AUR package about a missing dependency.

Fixed 👍🏻

**Pull request merged**
